# Site settings
title: Muhammad Abdullah
description: 'Python/Django Developer'
url: 'https://github.com/ranahaani'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-108070026-1
font_awesome: 'f6ae1a008b.js'

author:
  name: 'Muhammad Abdullah'
  email: ranahaani@gmail.com
  twitter_username: ranahaani
  #facebook_username: ranahaanii
  github_username:  ranahaani
  linkedin_username:  ranahaani
  #meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
